name: Run Tests (light)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - develop
      - docs

jobs:

  Prepare:
    permissions:
      contents: read
      packages: write
    uses: miekkasarki/ascot5/.github/workflows/build.yaml@main

  Testing:
    needs: Prepare
    uses: miekkasarki/ascot5/.github/workflows/tests.yaml@main
    with:
      run_unit_tests: true
