name: (Reusable) Build
on: [workflow_call]

jobs:

  Build-Code:
    if: always() || failure()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: ascot-dev
          auto-update-conda: true
          use-only-tar-bz2: true
          python-version: "3.10"

      - name: Current Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('environment-dev.yaml') }}
        id: cache

      - name: Update environment
        run:
          mamba env update -n ascot-dev -f
          environment-dev.yaml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Make ascot5_main with MPI
        run: make ascot5_main MPI=1 -j

      - name: Make clean
        run: make clean

      - name: Make ascot5_main without MPI
        run: make ascot5_main CC=h5pcc -j

      - name: Make libascot.so
        run: make libascot CC=h5pcc

      - name: Make BBNBI
        run: make bbnbi5 CC=h5pcc

      - name: Make ascot2py
        run: make ascot2py.py CC=h5pcc

      - name: Set permissions and pack
        run: |
          cd ./build
          chmod +x ascot5_main bbnbi5
          tar -cf code.tar ascot5_main bbnbi5 libascot.so
          cd ..

      - name: Upload code
        uses: actions/upload-artifact@main
        with:
          name: code
          path: ./build/code.tar

      - name: Upload ascot2py.py
        uses: actions/upload-artifact@main
        with:
          name: ascot2py
          path: ./a5py/ascotpy/ascot2py.py
